"""Action entrypoint for the predict workflow.

Reads issue env vars, runs predict(), posts a markdown comment, updates state.
"""
from __future__ import annotations

import os
import sys
import traceback
from datetime import date
from pathlib import Path

import httpx

if __package__ is None:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.predict import predict
from scripts.utils import (
    ROOT,
    STATE_DIR,
    VALID_DATE,
    check_rate_limit,
    load_json,
    parse_issue_form,
    sanitize,
    save_json,
    update_usage,
)

LATEST_PATH = STATE_DIR / "latest_prediction.json"
LOG_PATH = STATE_DIR / "predictions_log.json"
USAGE_PATH = STATE_DIR / "usage.json"
REASONS_PATH = ROOT / "reasons.md"


def _conf_emoji(p: float) -> str:
    if p >= 0.5:
        return "🟢"
    if p >= 0.25:
        return "🟡"
    return "🔴"


def format_comment(prediction: dict) -> str:
    venue = prediction.get("venue", "")
    date_str = prediction.get("date", "")
    city = prediction.get("city", "")
    venue_line = f"{venue}{(' — ' + city) if city else ''} — {date_str}"
    header = f"## 🎸 Phinish Prediction\n\n**{venue_line}**\n"
    parts = [header]
    for set_key, label in (("1", "Set 1"), ("2", "Set 2"), ("encore", "Encore")):
        items = prediction.get("setlist", {}).get(set_key, [])
        if not items:
            continue
        parts.append(f"\n### {label}\n")
        parts.append("| # | Song | Confidence | Gap |\n|---|------|-----------|-----|")
        for i, item in enumerate(items, 1):
            conf = item.get("confidence", 0.0)
            gap = item.get("gap", 0)
            parts.append(
                f"| {i} | {item['song']} | {_conf_emoji(conf)} {conf:.0%} | "
                f"{gap} show{'s' if gap != 1 else ''} |"
            )
        parts.append("")
    weights = prediction.get("weights", {})
    parts.append(
        f"\n---\n**Avg Confidence:** {prediction.get('avg_confidence', 0.0):.0%} • "
        f"**Weights:** xgb={weights.get('xgboost', 0):.2f} markov={weights.get('markov', 0):.2f} "
        f"gap={weights.get('gap', 0):.2f} venue={weights.get('venue', 0):.2f}\n"
        "_Generated by [Phinish](../tree/main)._"
    )
    return "\n".join(parts)


def post_comment(repo: str, issue_number: int, body: str, token: str) -> None:
    r = httpx.post(
        f"https://api.github.com/repos/{repo}/issues/{issue_number}/comments",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json={"body": body},
        timeout=30.0,
    )
    r.raise_for_status()


def append_reasons(prediction: dict, issue_number: int, author: str) -> None:
    REASONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    venue = prediction.get("venue", "")
    avg = prediction.get("avg_confidence", 0.0)
    line = (
        f"\n## #{issue_number} — {prediction.get('date', '')} @ {venue} "
        f"(@{author}, generated {today})\n\n"
        f"Avg confidence: {avg:.0%}. Top picks across sets: "
        + ", ".join(
            item["song"]
            for set_key in ("1", "2", "encore")
            for item in prediction.get("setlist", {}).get(set_key, [])[:2]
        )
        + ".\n"
    )
    with REASONS_PATH.open("a", encoding="utf-8") as f:
        f.write(line)


def main() -> None:
    issue_number = int(os.environ.get("ISSUE_NUMBER", "0"))
    body = os.environ.get("ISSUE_BODY", "")
    author = sanitize(os.environ.get("ISSUE_AUTHOR", "anonymous"), 64)
    token = os.environ.get("GITHUB_TOKEN", "")
    repo = os.environ.get("GITHUB_REPOSITORY", "")

    fields = parse_issue_form(body)
    date_str = sanitize(fields.get("show date", ""), 32)
    venue = sanitize(fields.get("venue", ""), 200)
    city = sanitize(fields.get("city", ""), 200) or None

    if not VALID_DATE.match(date_str):
        msg = f"❌ Invalid or missing date: `{date_str}`. Expected `YYYY-MM-DD`."
        if token and repo and issue_number:
            post_comment(repo, issue_number, msg, token)
        raise SystemExit(msg)
    if not venue:
        msg = "❌ Missing venue."
        if token and repo and issue_number:
            post_comment(repo, issue_number, msg, token)
        raise SystemExit(msg)

    usage = load_json(USAGE_PATH) if USAGE_PATH.exists() else {}
    ok, reason = check_rate_limit(usage, author)
    if not ok:
        msg = f"⏳ Rate limited: {reason}"
        if token and repo and issue_number:
            post_comment(repo, issue_number, msg, token)
        raise SystemExit(msg)

    try:
        prediction = predict(date_str, venue, city)
    except Exception as e:
        tb = traceback.format_exc()
        print(tb, file=sys.stderr)
        if token and repo and issue_number:
            post_comment(repo, issue_number,
                         f"❌ Prediction failed: `{type(e).__name__}: {e}`")
        raise

    comment_body = format_comment(prediction)
    if token and repo and issue_number:
        post_comment(repo, issue_number, comment_body, token)
    else:
        print(comment_body)

    save_json(LATEST_PATH, prediction)

    log = load_json(LOG_PATH) if LOG_PATH.exists() else []
    log.append({
        "issue_number": issue_number,
        "author": author,
        "date": prediction["date"],
        "venue": prediction["venue"],
        "venue_id": prediction.get("venue_id", ""),
        "avg_confidence": prediction.get("avg_confidence", 0.0),
        "generated_at": date.today().isoformat(),
    })
    save_json(LOG_PATH, log)

    save_json(USAGE_PATH, update_usage(usage, author))
    append_reasons(prediction, issue_number, author)
    print(f"prediction posted to issue #{issue_number}")


if __name__ == "__main__":
    main()
