"""Action entrypoint for the predict workflow.

Reads issue env vars, runs predict(), posts a markdown comment, updates state.
"""

import os
import sys
import traceback
from dataclasses import dataclass
from datetime import date
from typing import NoReturn

import msgspec

from phinish.predict.pipeline import predict
from phinish.predict.types import Prediction
from phinish.process.types import Usage
from phinish.summarize.api import summarize
from phinish.utils import (
    ROOT,
    SET_DISPLAY,
    STATE_DIR,
    VALID_DATE,
    check_rate_limit,
    load_json,
    parse_issue_form,
    post_issue_comment,
    sanitize,
    save_json,
    update_usage,
)

LATEST_PATH = STATE_DIR / "latest_prediction.json"
LOG_PATH = STATE_DIR / "predictions_log.json"
USAGE_PATH = STATE_DIR / "usage.json"
REASONS_PATH = ROOT / "reasons.md"


@dataclass(slots=True)
class _IssueRequest:
    """Parsed environment variables for a prediction-request issue."""

    issue_number: int
    body: str
    author: str
    token: str
    repo: str

    @property
    def can_post(self) -> bool:
        return bool(self.token and self.repo and self.issue_number)


def _conf_emoji(p: float) -> str:
    """Map a confidence probability to a green / yellow / red emoji."""
    if p >= 0.5:
        return "🟢"
    if p >= 0.25:
        return "🟡"
    return "🔴"


def _set_table(items: list) -> list[str]:
    """Build markdown table rows for one set's predicted songs."""
    rows = ["| # | Song | Confidence | Gap |\n|---|------|-----------|-----|"]
    for i, item in enumerate(items, 1):
        rows.append(
            f"| {i} | {item.song} | {_conf_emoji(item.confidence)} {item.confidence:.0%} | "
            f"{item.gap} show{'s' if item.gap != 1 else ''} |"
        )
    return rows


def format_comment(prediction: Prediction, summary_text: str | None = None) -> str:
    """Render a prediction as a markdown comment for posting on a GitHub issue.

    Parameters
    ----------
    prediction
        The structured prediction returned by ``phinish.predict.pipeline.predict``.
    summary_text
        Optional LLM-generated summary. Inserted as a blockquote section
        titled "The Vibe" between the setlist tables and the footer.

    Returns
    -------
    str
        Markdown body suitable for ``post_issue_comment``.
    """
    city_part = f" — {prediction.city}" if prediction.city else ""
    venue_line = f"{prediction.venue}{city_part} — {prediction.date}"
    parts = [f"## 🎸 Phinish Prediction\n\n**{venue_line}**\n"]
    for set_key, label in SET_DISPLAY:
        items = prediction.setlist.get(set_key, [])
        if not items:
            continue
        parts.append(f"\n### {label}\n")
        parts.extend(_set_table(items))
        parts.append("")
    if summary_text:
        parts.append(f"\n### The Vibe\n> {summary_text}\n")
    w = prediction.weights
    parts.append(
        f"\n---\n**Avg Confidence:** {prediction.avg_confidence:.0%} • "
        f"**Weights:** xgb={w.xgboost:.2f} markov={w.markov:.2f} "
        f"gap={w.gap:.2f} venue={w.venue:.2f}\n"
        "_Generated by [Phinish](../tree/main)._"
    )
    return "\n".join(parts)


def append_reasons(prediction: Prediction, issue_number: int, author: str) -> None:
    """Append a one-paragraph audit entry for this prediction to reasons.md.

    Parameters
    ----------
    prediction
        The prediction payload.
    issue_number
        GitHub issue id.
    author
        GitHub login of the issue author.
    """
    REASONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    today = date.today().isoformat()
    top_picks = ", ".join(
        item.song
        for set_key, _ in SET_DISPLAY
        for item in prediction.setlist.get(set_key, [])[:2]
    )
    line = (
        f"\n## #{issue_number} — {prediction.date} @ {prediction.venue} "
        f"(@{author}, generated {today})\n\n"
        f"Avg confidence: {prediction.avg_confidence:.0%}. Top picks across sets: {top_picks}.\n"
    )
    with REASONS_PATH.open("a", encoding="utf-8") as f:
        f.write(line)


def _read_request() -> _IssueRequest:
    """Build an ``_IssueRequest`` from the GitHub Actions environment."""
    return _IssueRequest(
        issue_number=int(os.environ.get("ISSUE_NUMBER", "0")),
        body=os.environ.get("ISSUE_BODY", ""),
        author=sanitize(os.environ.get("ISSUE_AUTHOR", "anonymous"), 64),
        token=os.environ.get("GITHUB_TOKEN", ""),
        repo=os.environ.get("GITHUB_REPOSITORY", ""),
    )


def _fail(req: _IssueRequest, msg: str) -> NoReturn:
    """Post an error comment to the issue and exit with a non-zero status."""
    if req.can_post:
        post_issue_comment(req.repo, req.issue_number, msg, req.token)
    raise SystemExit(msg)


def _persist_outputs(prediction: Prediction, req: _IssueRequest, usage: Usage) -> None:
    """Write latest prediction, append to log, update usage, and record reasons."""
    save_json(LATEST_PATH, prediction)
    log = load_json(LOG_PATH) if LOG_PATH.exists() else []
    log.append({
        "issue_number": req.issue_number,
        "author": req.author,
        "date": prediction.date,
        "venue": prediction.venue,
        "venue_id": prediction.venue_id,
        "avg_confidence": prediction.avg_confidence,
        "generated_at": date.today().isoformat(),
    })
    save_json(LOG_PATH, log)
    save_json(USAGE_PATH, update_usage(usage, req.author))
    append_reasons(prediction, req.issue_number, req.author)


def process_issue() -> None:
    """Validate the issue, run predict, post the comment, and persist outputs."""
    req = _read_request()
    fields = parse_issue_form(req.body)
    date_str = sanitize(fields.get("show date", ""), 32)
    venue = sanitize(fields.get("venue", ""), 200)
    city = sanitize(fields.get("city", ""), 200) or None
    voice = sanitize(fields.get("summary voice", ""), 64) or "Full Phan"

    if not VALID_DATE.match(date_str):
        _fail(req, f"❌ Invalid or missing date: `{date_str}`. Expected `YYYY-MM-DD`.")
    if not venue:
        _fail(req, "❌ Missing venue.")

    usage_raw = load_json(USAGE_PATH) if USAGE_PATH.exists() else {}
    usage = msgspec.convert(usage_raw, Usage, strict=False) if usage_raw else Usage()
    ok, reason = check_rate_limit(usage, req.author)
    if not ok:
        _fail(req, f"⏳ Rate limited: {reason}")

    try:
        prediction = predict(date_str, venue, city)
    except Exception as e:
        print(traceback.format_exc(), file=sys.stderr)
        if req.can_post:
            post_issue_comment(req.repo, req.issue_number,
                               f"❌ Prediction failed: `{type(e).__name__}: {e}`",
                               req.token)
        raise

    summary = summarize(prediction, voice)
    comment_body = format_comment(prediction, summary_text=summary.text)
    if req.can_post:
        post_issue_comment(req.repo, req.issue_number, comment_body, req.token)
    else:
        print(comment_body)

    _persist_outputs(prediction, req, usage)
    print(f"prediction posted to issue #{req.issue_number}")


if __name__ == "__main__":
    process_issue()
